mode: base
seed: 42
output_dir: results

evaluations:
  - perplexity
  - holistic_bias
  - sofa

perplexity:
  dataset_path: Salesforce/wikitext
  dataset_name: wikitext-2-raw-v1
  split: test
  text_column: text
  n_ctx: 1024
  stride: 512


holistic_bias:
  dataset: iproskurina/holisticbias-sentiment-pairs
  split: train
  batch_size: 64

sofa:
  dataset: iproskurina/sofa-sampled-250-each
  split: train
  identity_file: data/sofa/identities_by_category.json
  batch_size: 512
  max_length: 32

lm_eval:
  - backend: hf
    tasks:
      - bbq
      - crows_pairs_english
    batch_size: 8
    device: cuda:0